stages:
    - deploy

.deploy: &deploy
    stage: deploy
    script:
        - deployer --env=$ENVIRONMENT --project-name=$CI_PROJECT_NAME

deploy_dev:
    <<: *deploy
    variables: 
        ENVIRONMENT: "dev"
    environment:
        url: "https://dev.hand.technology/"
        name: $ENVIRONMENT

deploy_prd:
    <<: *deploy
    variables: 
        ENVIRONMENT: "prod"
    environment:
        url: "https://keithhand.dev/"
        name: $ENVIRONMENT
    only:
        - master
    when: manual