stages:
    - build
    - test
    - deploy

.default: &default
    variables: 
        ENVIRONMENT: "dev"
    script:
        - deployer --env=$ENVIRONMENT --project-name=$CI_PROJECT_NAME $CI_JOB_STAGE

.deploy: &deploy
    <<: *default
    stage: deploy

build:
    <<: *default
    stage: build

test:
    <<: *default
    stage: test

deploy_dev:
    <<: *deploy
    variables: 
        ENVIRONMENT: "dev"
    environment:
        url: "https://dev.hand.technology/"
        name: $ENVIRONMENT

deploy_prd:
    <<: *deploy
    variables: 
        ENVIRONMENT: "prod"
    environment:
        url: "https://keithhand.dev/"
        name: $ENVIRONMENT
    when: manual