stages:
    - deploy

.deploy: &deploy
    script:
        - docker-compose -f ./private/docker/docker-compose.$ENVIRONMENT.yml up -d --build
    after_script:
        - echo "successful deployment"

deploy_dev:
    <<: *deploy
    stage: deploy
    before_script: 
        - check-dev-server
    variables: 
        ENVIRONMENT: "dev"
    environment:
        url: "https://dev.hand.technology/"
        name: $ENVIRONMENT

deploy_prd:
    <<: *deploy
    stage: deploy
    variables: 
        ENVIRONMENT: "prod"
    environment:
        url: "https://keithhand.dev/"
        name: $ENVIRONMENT
    only:
        - master
    when: manual