stages:
    - deploy

.deploy: &deploy
    script:
        - curl -i "http://hand.technology:8080/?sha=$CI_COMMIT_SHA&pname=$CI_PROJECT_NAME&branch=$CI_COMMIT_REF_NAME"

deploy_prd:
    <<: *deploy
    stage: deploy
    environment:
        name: "prd"
