stages:
    - deploy

.deploy: &deploy
    script:
        - curl -f "https://deploy.hand.technology/?sha=$CI_COMMIT_SHA&pname=$CI_PROJECT_NAME"

deploy_prd:
    <<: *deploy
    stage: deploy
    environment:
        name: "production"
        url: "https://keithhand.dev/"