version: '3'
services:
  php:
    container_name: personal-webpage-php
    build: './php/'
    networks:
      - backend
    volumes:
      - ./public_html/:/var/www/html/
    restart: always
  apache:
    container_name: personal-webpage-apache
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./public_html/:/var/www/html/
    restart: always
networks:
  frontend:
  backend:
