version: '3'
services:
  php:
    container_name: personal-webpage-php
    build: './php/'
    volumes:
      - ./public_html/:/var/www/html/
    restart: always
  apache:
    container_name: personal-webpage-apache
    build: './apache/'
    depends_on:
      - php
    volumes:
      - ./public_html/:/var/www/html/
    ports:
      - "80:80"
    restart: always
