version: '3'
services:
    web:
        container_name: personal-webpage
        build: 
            context: ../..
            dockerfile: private/docker/prod.Dockerfile
        ports:
            - "8000:8000"