version: '3'
services:
    web:
        container_name: personal-webpage
        build: 
            context: ../..
            dockerfile: private/docker/prod.Dockerfile
        environment:
            - VIRTUAL_HOST=hand.technology
            - VIRTUAL_PORT=8000